export type Language = 'en' | 'ro';

export interface LanguageConfig {
  code: Language;
  name: string;
  flag: string;
}

export const languages: LanguageConfig[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'ro', name: 'Română', flag: '🇷🇴' }
];

export const defaultLanguage: Language = 'en';

// Language data
export const translations = {
  en: {
    // Header
    searchPlaceholder: "Search products...",
    tagline: "Professional Tableware & Kitchen Equipment",
    freeDelivery: "Free delivery on orders over RON 200",
    returnPolicy: "30-day return policy",
    location: "Bucharest, Romania",
    phone: "+40 123 456 789",
    
    // Navigation
    home: "Home",
    categories: "Categories",
    products: "Products",
    cart: "Cart",
    favorites: "Favorites",
    account: "Account",
    
    // Common
    addToCart: "Add to Cart",
    addedToCart: "Added to Cart",
    addToFavorites: "Add to Favorites",
    buyNow: "Buy Now",
    viewMore: "View More",
    signUp: "Sign Up",
    signIn: "Sign In",
    
    // Search
    searchResults: "Search Results",
    filters: "Filters",
    searchFilters: "Search Filters",
    priceRange: "Price Range",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    priceSorting: "Price Sorting",
    noSorting: "No sorting",
    priceLowToHigh: "Price: Low to High",
    priceHighToLow: "Price: High to Low",
    clear: "Clear",
    apply: "Apply",
    showingResultsFor: "Showing results for",
    productsFound: "products found",
    searching: "Searching...",
    noProductsFound: "No products found",
    tryAdjustingSearch: "Try adjusting your search terms or filters to find what you're looking for.",
    
    // Services
    horecaEquipmentTitle: "Horeca Equipment for your business",
    designConsultancy: "3D DESIGN AND CONSULTANCY",
    designConsultancyDesc: "Personalized solutions for your business",
    financingPayment: "FINANCING AND PAYMENT",
    financingPaymentDesc: "Flexible payment options",
    freeDeliveryService: "FREE DELIVERY IN BUCHAREST",
    freeDeliveryServiceDesc: "Fast and secure delivery",
    installationCommissioning: "INSTALLATION AND COMMISSIONING",
    installationCommissioningDesc: "Professional installation",
    maintenanceService: "MAINTENANCE, REVISIONS AND SERVICE",
    maintenanceServiceDesc: "Complete technical support",
    
    // Product
    description: "Description",
    selectSize: "Select Size",
    sizeGuide: "Size Guide",
    relatedProducts: "Related Products",
    selectOptions: "Select Options",
    forMoreDetails: "For more details:",

    // About page
    backToHome: "← Back to Home",
    excellence: "Excellence!",
    transformYour: "Transform Your",
    hospitality: " Hospitality",
    aboutHeroSubtitle: "Explore a comprehensive range of premium tableware and kitchen equipment designed to elevate your dining experience and professional kitchen operations.",
    exploreProducts: "Explore Products",
    contactUs: "Contact Us",
    yearsOfExperience: "Years of experience",
    happyCustomers: "Happy customers",
    premiumProducts: "Premium products",
    premiumQuality: "Premium Quality",
    professionalGrade: "Professional Grade",
    bestServices: "Best Services",
    bucharestRomania: "Bucharest, Romania",
    servicesRangeTitle: "We offer a wide range of services to meet your needs",
    distributedProducts: "Distributed products",
    revolutionary: "Revolutionary!",
    servicesRangeDesc: "Our services are designed to provide the best hospitality equipment solutions. We are committed to delivering tailored solutions, experienced professionals, and state-of-the-art products that meet the highest industry standards.",
    shopNow: "Shop Now",
    learnMore: "Learn More",
    servicesPowerTitle: "Discover the Power of Our Services",
    servicesPowerDesc: "Explore a variety of tailored services aimed at enhancing your hospitality business and kitchen operations.",
    svcPremiumTablewareTitle: "Premium Tableware Collection",
    svcPremiumTablewareDesc: "We offer a comprehensive collection of premium plates, bowls, cups, and cutlery designed for professional use and elegant presentation.",
    svcProKitchenEquipTitle: "Professional Kitchen Equipment",
    svcProKitchenEquipDesc: "Complete range of pots, pans, sauciers, and cooking equipment built to withstand the demands of commercial kitchens.",
    svcCustomBrandingTitle: "Custom Branding Solutions",
    svcCustomBrandingDesc: "Personalized tableware and equipment with your restaurant's logo and branding for a unique dining experience.",
    svcWholesaleTitle: "Bulk Ordering & Wholesale",
    svcWholesaleDesc: "Specialized wholesale services for restaurants, hotels, and hospitality businesses with volume discounts and bulk pricing.",
    svcConsultationTitle: "Expert Consultation",
    svcConsultationDesc: "Professional guidance from our hospitality experts to help you choose the right equipment for your specific needs and budget.",
    svcAfterSalesTitle: "After-Sales Support",
    svcAfterSalesDesc: "Comprehensive support including maintenance advice, replacement parts, and ongoing customer service for all our products.",
    progressTitle: "Revolutionary! The services are designed to provide progress to your hospitality business.",
    progressDesc: "Our comprehensive services support the overall growth and success of your hospitality business. We view hospitality as a journey of continuous improvement, offering a holistic approach with professional support and premium equipment solutions.",
    qualityCheck: "Quality Check",
    verified100: "100% Verified",
    qualityProgress: "Quality Progress",
    premiumStandards: "Premium Standards",
    howItWorksTitle: "How does the process work to provide service?",
    step01: "01",
    stepExpertConsultationTitle: "Expert Consultation",
    stepExpertConsultationDesc: "Our hospitality experts will assess your needs and provide personalized recommendations for the best equipment solutions.",
    step02: "02",
    stepCustomizedSelectionTitle: "Customized Selection",
    stepCustomizedSelectionDesc: "Based on your requirements, we'll curate a selection of premium products that match your budget and specifications.",
    step03: "03",
    stepQualityAssuranceTitle: "Quality Assurance",
    stepQualityAssuranceDesc: "Every product undergoes rigorous quality checks to ensure it meets our premium standards before delivery.",
    step04: "04",
    stepFastDeliveryTitle: "Fast Delivery",
    stepFastDeliveryDesc: "We ensure quick and secure delivery of your products with real-time tracking and professional packaging.",
    step05: "05",
    stepOngoingSupportTitle: "Ongoing Support",
    stepOngoingSupportDesc: "Receive continuous support and maintenance advice to keep your equipment in perfect condition.",
    faqTitle: "Revolutionary! Frequently asked questions",
    faqSubtitle: "Contact us if you need immediate assistance",
    faqQ1: "What products do you offer?",
    faqA1: "We offer a comprehensive range including premium tableware, professional kitchen equipment, cutlery, serving dishes, and custom branding solutions for hospitality businesses.",
    faqQ2: "How do I place an order?",
    faqA2: "You can place orders through our website, by phone, or by contacting our sales team directly. We also offer bulk ordering and wholesale services for businesses.",
    faqQ3: "What is your return policy?",
    faqA3: "We offer a 30-day return policy for most items in original condition. Certain items may have specific return restrictions due to hygiene or safety reasons.",
    faqQ4: "Do you ship internationally?",
    faqA4: "Yes, we ship to most countries. Shipping costs and delivery times vary by location. Contact us for specific international shipping information.",
    faqQ5: "Can you customize products with our branding?",
    faqA5: "Absolutely! We offer custom branding services for tableware and equipment. Contact our team to discuss your specific branding requirements.",
    ctaTitle: "Ready to Transform Your Hospitality Business?",
    ctaDesc: "Let our experts help you choose the perfect equipment solutions for your restaurant, hotel, or hospitality business.",
    getInTouch: "Get in Touch",

    // Terms page
    termsIntro1: "These Terms of Service (\"Terms\") govern your use of the EGM HORECA website and services.",
    termsIntro2: "By accessing or using our website, you agree to be bound by these Terms.",
    termsIntro3: "These Terms apply to all visitors, users, and others who access or use our Service.",
    acceptanceOfTerms: "Acceptance of Terms",
    useLicense: "Use License",
    userAccounts: "User Accounts",
    productInfoPricing: "Product Information and Pricing",
    orderingPayment: "Ordering and Payment",
    shippingDelivery: "Shipping and Delivery",
    returnsRefunds: "Returns and Refunds",
    intellectualProperty: "Intellectual Property",
    prohibitedUses: "Prohibited Uses",
    limitationOfLiability: "Limitation of Liability",
    disclaimerOfWarranties: "Disclaimer of Warranties",
    governingLaw: "Governing Law",
    changesToTerms: "Changes to Terms",
    contactInformation: "Contact Information",
    
    // Cart
    subtotal: "Subtotal",
    discount: "Discount",
    delivery: "Delivery",
    tax: "Tax",
    total: "Total",
    checkout: "Checkout",
    
    // Account
    firstName: "First Name",
    lastName: "Last Name",
    username: "Username or Email",
    password: "Password",
    confirmPassword: "Confirm New Password",
    communicationPolicy: "Electronics Communication Policy",
    
    // Footer
    about: "About",
    aboutUs: "About Us",
    contact: "Contact",
    support: "Support",
    terms: "Terms",
    legal: "Legal",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    shippingInfo: "Shipping Info",
    returns: "Returns",
    quickLinks: "Quick Links",
    
    search: "Search",
    plates: "Plates",
    cups: "Cups",
    cutlery: "Cutlery",
    bottomTagline: "Professional Tableware & Kitchen Equipment",
    rightsReserved: "All rights reserved.",
    copyright: "Copyright 2024"
  },
  ro: {
    // Header
    searchPlaceholder: "Caută produse...",
    tagline: "Veselă profesională și echipamente de bucătărie",
    freeDelivery: "Livrare gratuită pentru comenzi peste 200 RON",
    returnPolicy: "Politica de returnare 30 zile",
    location: "București, România",
    phone: "+40 123 456 789",
    
    // Navigation
    home: "Acasă",
    categories: "Categorii",
    products: "Produse",
    cart: "Coș",
    favorites: "Favorite",
    account: "Cont",
    
    // Common
    addToCart: "Adaugă în Coș",
    addedToCart: "Adăugat în Coș",
    addToFavorites: "Adaugă la Favorite",
    buyNow: "Cumpără Acum",
    viewMore: "Vezi Mai Mult",
    signUp: "Înregistrare",
    signIn: "Autentificare",
    
    // Search
    searchResults: "Rezultate Căutare",
    filters: "Filtre",
    searchFilters: "Filtre Căutare",
    priceRange: "Interval Preț",
    minPrice: "Preț Minim",
    maxPrice: "Preț Maxim",
    priceSorting: "Sortare Preț",
    noSorting: "Fără sortare",
    priceLowToHigh: "Preț: Mic la Mare",
    priceHighToLow: "Preț: Mare la Mic",
    clear: "Șterge",
    apply: "Aplică",
    showingResultsFor: "Afișez rezultate pentru",
    productsFound: "produse găsite",
    searching: "Căutare...",
    noProductsFound: "Nu au fost găsite produse",
    tryAdjustingSearch: "Încearcă să modifici termenii de căutare sau filtrele pentru a găsi ceea ce cauți.",
    
    // Services
    horecaEquipmentTitle: "Echipamente Horeca pentru afacerea ta",
    designConsultancy: "PROIECTARE 3D SI CONSULTANTA",
    designConsultancyDesc: "Soluții personalizate pentru afacerea ta",
    financingPayment: "FINANTARE SI PLATA",
    financingPaymentDesc: "Opțiuni flexibile de plată",
    freeDeliveryService: "LIVRARE GRATUITA IN BUCURESTI",
    freeDeliveryServiceDesc: "Livrare rapidă și sigură",
    installationCommissioning: "MONTAJ SI PUNERE IN FUNCTIUNE",
    installationCommissioningDesc: "Instalare profesională",
    maintenanceService: "MENTENANTA, REVIZII SI SERVICE",
    maintenanceServiceDesc: "Suport tehnic complet",
    
    // Product
    description: "Descriere",
    selectSize: "Selectează Mărimea",
    sizeGuide: "Ghid Mărimi",
    relatedProducts: "Produse Similare",
    selectOptions: "Selectează opțiunile",
    forMoreDetails: "Pentru mai multe detalii:",

    // About page
    backToHome: "← Înapoi la Acasă",
    excellence: "Excelență!",
    transformYour: "Transformă-ți",
    hospitality: " ospitalitatea",
    aboutHeroSubtitle: "Descoperă o gamă completă de veselă premium și echipamente de bucătărie concepute pentru a ridica experiența la masă și operațiunile profesionale din bucătărie.",
    exploreProducts: "Vezi Produsele",
    contactUs: "Contactează-ne",
    yearsOfExperience: "Ani de experiență",
    happyCustomers: "Clienți fericiți",
    premiumProducts: "Produse premium",
    premiumQuality: "Calitate Premium",
    professionalGrade: "Nivel Profesional",
    bestServices: "Cele mai bune servicii",
    bucharestRomania: "București, România",
    servicesRangeTitle: "Oferim o gamă largă de servicii pentru nevoile tale",
    distributedProducts: "Produse distribuite",
    revolutionary: "Revoluționar!",
    servicesRangeDesc: "Serviciile noastre sunt concepute pentru a oferi cele mai bune soluții de echipamente pentru ospitalitate. Oferim soluții personalizate, profesioniști cu experiență și produse de ultimă generație care respectă cele mai înalte standarde.",
    shopNow: "Cumpără acum",
    learnMore: "Află mai mult",
    servicesPowerTitle: "Descoperă puterea serviciilor noastre",
    servicesPowerDesc: "Explorează o varietate de servicii personalizate menite să îți îmbunătățească afacerea de ospitalitate și operațiunile din bucătărie.",
    svcPremiumTablewareTitle: "Colecție de veselă premium",
    svcPremiumTablewareDesc: "Oferim o colecție cuprinzătoare de farfurii, boluri, căni și tacâmuri premium, concepute pentru uz profesional și prezentare elegantă.",
    svcProKitchenEquipTitle: "Echipamente profesionale de bucătărie",
    svcProKitchenEquipDesc: "Gamă completă de oale, tigăi, sosniere și echipamente de gătit concepute pentru a rezista cerințelor bucătăriilor comerciale.",
    svcCustomBrandingTitle: "Soluții de branding personalizat",
    svcCustomBrandingDesc: "Veselă și echipamente personalizate cu logo-ul și brandingul restaurantului tău pentru o experiență unică.",
    svcWholesaleTitle: "Comenzi în volum și en-gros",
    svcWholesaleDesc: "Servicii specializate en-gros pentru restaurante, hoteluri și afaceri din ospitalitate, cu reduceri pentru volum.",
    svcConsultationTitle: "Consultanță de specialitate",
    svcConsultationDesc: "Ghidare profesională din partea experților noștri în ospitalitate pentru a alege echipamentele potrivite nevoilor și bugetului tău.",
    svcAfterSalesTitle: "Suport post-vânzare",
    svcAfterSalesDesc: "Suport cuprinzător, inclusiv sfaturi de mentenanță, piese de schimb și servicii clienți continue pentru toate produsele noastre.",
    progressTitle: "Revoluționar! Serviciile sunt concepute pentru a aduce progres afacerii tale din ospitalitate.",
    progressDesc: "Serviciile noastre complete susțin creșterea și succesul afacerii tale. Considerăm ospitalitatea un drum al îmbunătățirii continue, oferind o abordare holistică cu suport profesional și soluții premium.",
    qualityCheck: "Verificare calitate",
    verified100: "100% Verificat",
    qualityProgress: "Progresul calității",
    premiumStandards: "Standard premium",
    howItWorksTitle: "Cum funcționează procesul pentru a oferi serviciul?",
    step01: "01",
    stepExpertConsultationTitle: "Consultanță de specialitate",
    stepExpertConsultationDesc: "Experții noștri în ospitalitate îți vor evalua nevoile și îți vor oferi recomandări personalizate.",
    step02: "02",
    stepCustomizedSelectionTitle: "Selecție personalizată",
    stepCustomizedSelectionDesc: "Pe baza cerințelor tale, vom crea o selecție de produse premium potrivite bugetului și specificațiilor.",
    step03: "03",
    stepQualityAssuranceTitle: "Asigurarea calității",
    stepQualityAssuranceDesc: "Fiecare produs trece prin verificări riguroase de calitate înainte de livrare.",
    step04: "04",
    stepFastDeliveryTitle: "Livrare rapidă",
    stepFastDeliveryDesc: "Asigurăm livrarea rapidă și sigură a produselor, cu urmărire în timp real și ambalare profesională.",
    step05: "05",
    stepOngoingSupportTitle: "Suport continuu",
    stepOngoingSupportDesc: "Primești suport și sfaturi de mentenanță pentru a menține echipamentele în stare perfectă.",
    faqTitle: "Revoluționar! Întrebări frecvente",
    faqSubtitle: "Contactează-ne dacă ai nevoie de asistență imediată",
    faqQ1: "Ce produse oferiți?",
    faqA1: "Oferim o gamă cuprinzătoare care include veselă premium, echipamente profesionale de bucătărie, tacâmuri, tăvi de servire și soluții de branding personalizate.",
    faqQ2: "Cum plasez o comandă?",
    faqA2: "Poți plasa comenzi pe site, telefonic sau contactând direct echipa noastră de vânzări. Oferim și comenzi en-gros pentru afaceri.",
    faqQ3: "Care este politica de retur?",
    faqA3: "Oferim o politică de retur de 30 de zile pentru majoritatea articolelor în stare originală. Unele articole pot avea restricții specifice din motive de igienă sau siguranță.",
    faqQ4: "Livrați internațional?",
    faqA4: "Da, livrăm în majoritatea țărilor. Costurile și timpii de livrare variază în funcție de locație. Contactează-ne pentru detalii.",
    faqQ5: "Puteți personaliza produsele cu branding-ul nostru?",
    faqA5: "Desigur! Oferim servicii de branding personalizat pentru veselă și echipamente. Contactează echipa noastră pentru detalii.",
    ctaTitle: "Ești gata să-ți transformi afacerea din ospitalitate?",
    ctaDesc: "Lasă experții noștri să te ajute să alegi soluțiile perfecte de echipamente pentru restaurantul, hotelul sau afacerea ta.",
    getInTouch: "Contactează-ne",

    // Terms page
    termsIntro1: "Acești Termeni de Serviciu (\"Termeni\") reglementează utilizarea site-ului și serviciilor EGM HORECA.",
    termsIntro2: "Prin accesarea sau utilizarea site-ului nostru, ești de acord cu acești Termeni.",
    termsIntro3: "Acești Termeni se aplică tuturor vizitatorilor, utilizatorilor și altor persoane care accesează sau folosesc Serviciul nostru.",
    acceptanceOfTerms: "Acceptarea Termenilor",
    useLicense: "Licență de utilizare",
    userAccounts: "Conturi de utilizator",
    productInfoPricing: "Informații despre produse și prețuri",
    orderingPayment: "Comenzi și Plăți",
    shippingDelivery: "Livrare și Expediere",
    returnsRefunds: "Retururi și Rambursări",
    intellectualProperty: "Proprietate intelectuală",
    prohibitedUses: "Utilizări interzise",
    limitationOfLiability: "Limitarea răspunderii",
    disclaimerOfWarranties: "Declinarea garanțiilor",
    governingLaw: "Legea aplicabilă",
    changesToTerms: "Modificări ale Termenilor",
    contactInformation: "Informații de contact",
    
    // Cart
    subtotal: "Subtotal",
    discount: "Reducere",
    delivery: "Livrare",
    tax: "Taxe",
    total: "Total",
    checkout: "Finalizează Comanda",
    
    // Account
    firstName: "Prenume",
    lastName: "Nume",
    username: "Nume utilizator sau Email",
    password: "Parolă",
    confirmPassword: "Confirmă Parola Nouă",
    communicationPolicy: "Politica de Comunicare Electronică",
    
    // Footer
    about: "Despre",
    aboutUs: "Despre Noi",
    contact: "Contact",
    support: "Suport",
    terms: "Termeni",
    legal: "Legal",
    privacyPolicy: "Politica de Confidențialitate",
    termsOfService: "Termeni și Condiții",
    shippingInfo: "Informații livrare",
    returns: "Returnări",
    quickLinks: "Linkuri rapide",
    
    search: "Căutare",
    plates: "Farfurii",
    cups: "Căni",
    cutlery: "Tacâmuri",
    bottomTagline: "Veselă profesională și echipamente de bucătărie",
    rightsReserved: "Toate drepturile rezervate.",
    copyright: "Copyright 2024"
  }
};

export function getTranslation(lang: Language, key: string): string {
  return translations[lang][key as keyof typeof translations[typeof lang]] || key;
}
